name: anombox
debug: true
full_url: http://antimatter-studios.com/anombox/v1
timezone: UTC

cors:
  allowed: https://wirfuerhongkong.org
  default: https://wirfuerhongkong.org

file:
  minimum_size: "1000000"
  maximum_size: "200000000"
  regex_pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9A-Za-z\-\_]+

docker:
  nginx: christhomas/anombox_nginx:latest
  phpfpm: christhomas/anombox_phpfpm:latest

url: antimatter-studios.com

storage_size: 100Gi

access_control:
  - username: chris
    password: d1dde346bcf0dbc8cb17b15dd5f7b20fb474db75
  - username: agnus
    password: dc1d4b8491ad555e267e086c7fbf23fbe920a738

